version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
      - 6443:6443
    # NOT WORKING
    environment:
      - KUBERNETES_NODE1=10.175.134.131
      - KUBERNETES_NODE2=10.175.134.132
      - KUBERNETES_LISTEN_PORT=6443