apiVersion: apps/v1
kind: Service
metadata:
  name: nginx-test-nodeport
  namespace: default
spec:
  type: NodePort
  selector:
    app: nginx-test
  ports:
    - name: web
      port: 80
      targetPort: web
      nodePort: 31111